analyzer:
  errors:
    no_leading_underscores_for_local_identifiers: ignore
    avoid_print: ignore 
    use_build_context_synchronously: ignore 
    unused_field: ignore 
    library_private_types_in_public_api: ignore 
    prefer_const_constructors: ignore
    unnecessary_brace_in_string_interps: ignore 
    non_constant_identifier_names: ignore 
    constant_identifier_names: ignore
    deprecated_member_use: ignore
    prefer_const_literals_to_create_immutables: ignore
    must_be_immutable: ignore
    unnecessary_null_in_if_null_operators: ignore

include: package:flutter_lints/flutter.yaml
