name: bat_loyalty_program_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
  
dependencies:
  # functional
  dio: ^5.4.3+1
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  package_info_plus: ^7.0.0
  device_info_plus: ^10.1.0
  country_state_city: ^0.1.6
  geocoding: ^3.0.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  # aws3
  amplify_core: ^2.2.0
  amplify_flutter: ^2.2.0
  amplify_auth_cognito: ^2.2.0
  amplify_authenticator: ^2.1.0
  amplify_storage_s3: ^2.2.0

  flutter:
    sdk: flutter

  # decoration
  flutter_launcher_icons: ^0.13.1
  custom_refresh_indicator: ^3.1.2
  floating_snackbar: ^1.0.3+1
  sticky_headers: ^0.3.0+2
  lottie: ^3.1.2
  font_awesome_flutter: ^10.7.0
    
  cupertino_icons: ^1.0.6
  http: ^1.2.1

dependency_overrides:
  package_info_plus: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.0
  
flutter:
  generate: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
  uses-material-design: true

  assets:
    - .env
    - assets/fonts/
    - assets/logos/
    - assets/lotties/
    - assets/images_examples/
    - assets/security_images/
    - assets/security_phrases/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/icon_launcher.png"
  min_sdk_android: 21